#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage"
  echo "  backup <catalog file> <dest. folder>"
else
  CREDENTIALS=$(head -n 1 $1)
  HOST=$(echo $CREDENTIALS | cut -d ':' -f 1)

  tail -n +2 $1 | while read line; do
    SHA=$(echo $line | cut -f 1 -d ' ')
    FTMP=$(echo $line | cut -c66-)
    FILENAME=$(printf %q "$FTMP")

    DEST=$2$SHA

    if [ ! -f "$DEST" ]; then
      scp $HOST:"$FILENAME" $DEST
      COPY_SHA=$(shasum -a 256 $DEST | cut -f 1 -d ' ')

      if [ "$SHA" != "$COPY_SHA" ]; then
        echo "FAIL: $DEST"
      fi

      tar -czf $DEST.tar.gz $DEST
      mv $DEST.tar.gz $DEST
    fi
  done
fi
