#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage"
  echo "  restore catalog-file destination-folder"
else
  CATALOG=$1
  BCK=`dirname $(dirname $CATALOG)`
  DST=$2

  mkdir -p $DST
  cat $CATALOG | while read line; do
    SHA=$(echo $line | cut -d ' ' -f 1)
    BCK_FILE="$(echo $line | cut -c66-)"
    FOLDER=$(dirname "$BCK_FILE")
    BASE=$(basename "$BCK_FILE")

    mkdir -p "$DST/$FOLDER"
    tar -xOzf $BCK/$SHA.tar.gz > "$DST/$FOLDER/$BASE"
  done
fi
