#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Usage"
  echo "  restore catalog-file backups-folder destination-folder"
else
  CATALOG=$1
  BCK=$2
  DEST=$3

  cat $1 | while read line; do
    SHA=$(echo $line | cut -d ' ' -f 1)
    FILENAME="$(echo $line | cut -c66-)"
    FOLDER=$(dirname "$FILENAME")
    BASE=$(basename "$FILENAME")

    mkdir -p "$DEST/$FOLDER"
    tar -xOzf $BCK/$SHA.tar.gz > "$DEST/$FOLDER/$BASE"
  done
fi
